### ISSUE TITLE
Dependency error when IsEnabled is false

### ISSUE THREAD

**Issue by drpeck** [thecogworks/Cogworks.CogFlare#8]
**Describe the bug**
500 error from CloudFlareCachePurgeApiController

Umbraco v13.Latest/ CogFlare v1.3

**To Reproduce**
1. Install CogFlare
2. Set settings to 
```
  "CogFlareSettings": {
    "ApiKey": "[redacted]",
    "Email": "david@agency.com",
    "Endpoint": "https://api.cloudflare.com/client/v4/zones/[redacted]/purge_cache",
    "KeyNodes": "1234",
    "IsEnabled": false,
    "Domain": "https://www.livedomain.com"
  }
```
4. Go the CogFlare backoffice dashboard
5. Click 'See Settings'
6. Console shows `exceptionMessage` in response of `https://localhost/umbraco/backoffice/api/CloudFlareCachePurgeApi/GetSettings` is `"Unable to resolve service for type 'Cogworks.CogFlare.Core.Services.ICloudFlareCachePurgeService' while attempting to activate 'Cogworks.CogFlare.Core.Controllers.APIs.CloudFlareCachePurgeApiController'."`

**Expected behavior**
No error. Statement saying that CogFlare is disabled, or Dashboard not added

**Screenshots**
![image](https://github.com/user-attachments/assets/ceb1215a-476b-4431-8150-ec6c2961b1df)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox

**Additional context**
Works when IsEnabled is set to true.

**Comment by imranhaidercogworks** [comment]
Hi David,

Thank you for raising this issue.

We have a new version of CogFlare being released this week that should resolve this problem. If the issue persists after updating, please let us know, and we’ll be happy to investigate further. 👍🏽

Best regards

**Comment by imranhaidercogworks** [comment]
Hi David,

The latest version of the package has been released and should contain fixes for your raised issue

Please let us know if there's any other things we can help you with 👍🏽

**Comment by drpeck** [comment]
Great stuff. Ta.
